apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeequeue
  labels:
    app: coffeequeue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffeequeue
  template:
    metadata:
      labels:
        app: coffeequeue
    spec:
      imagePullSecrets:
      - name: coffeequeue-secret
      containers:
      - name: coffeequeue
        image: 10.10.2.119:8081/stratalyze/coffeequeue:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command:
            - "wget"
            - "-q"
            - "--spider"
            - "http://localhost:8080/health"
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"