apiVersion: v1
kind: Secret
metadata:
  name: coffeequeue-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxMC4xMC4yLjExOTo4MDgxIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NllXUnRhVzVoWkcxcGJnPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson